CREATE TABLE if not exists users (
	Id CHAR(36) PRIMARY KEY,
	Email VARCHAR(255) NOT NULL UNIQUE,
	`Password` VARCHAR(255) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	IsActive BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT now()
);

CREATE TABLE if not exists favorites (
	Id CHAR(36) PRIMARY KEY,
	UserId CHAR(36) NOT NULL,
	StationId CHAR(36) NOT NULL,
	CreatedAt DATETIME DEFAULT NOW(),
	FOREIGN KEY (UserId) REFERENCES users(Id)
);

CREATE TABLE if not exists tags (
	Id CHAR(36) PRIMARY KEY,
	`Name` VARCHAR(50) NOT NULL UNIQUE,
	IsActive BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT NOW()
);